# Generated by Django 5.2.17 on 2026-09-22 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(blank=True, max_length=80)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('accent', models.CharField(default='brand', max_length=16)),
                ('size_min', models.PositiveSmallIntegerField(default=2)),
                ('size_max', models.PositiveSmallIntegerField(default=2)),
                ('target_gender', models.CharField(blank=True, choices=[('F', 'زن'), ('M', 'مرد')], max_length=1)),
                ('category', models.CharField(blank=True, choices=[('FRIENDLY', 'دوستانه'), ('FUNNY', 'خنده\u200cدار'), ('DEEP', 'عمیق'), ('BOLD', 'جسورانه')], max_length=10)),
                ('max_intensity', models.PositiveSmallIntegerField(default=2)),
                ('rounds', models.PositiveSmallIntegerField(default=3)),
                ('min_age', models.PositiveSmallIntegerField(default=18)),
                ('requires_premium', models.BooleanField(default=False)),
                ('daily_limit', models.PositiveSmallIntegerField(default=0)),
                ('widen_after_seconds', models.PositiveSmallIntegerField(default=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ('sort_order', 'key'),
            },
        ),
        migrations.CreateModel(
            name='MatchTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_gender', models.CharField(blank=True, max_length=1)),
                ('want_gender', models.CharField(blank=True, max_length=1)),
                ('size_min', models.PositiveSmallIntegerField(default=2)),
                ('size_max', models.PositiveSmallIntegerField(default=2)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(choices=[('QUEUED', 'در صف'), ('MATCHED', 'جور شد'), ('CANCELLED', 'لغو شد'), ('EXPIRED', 'منقضی شد')], default='QUEUED', max_length=10)),
                ('widened', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.matchmode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'created_at'], name='matchmaking_state_5ee68c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'QUEUED')), fields=('user',), name='one_active_ticket_per_user')],
            },
        ),
    ]
