# Generated by Django 5.2.17 on 2026-09-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmode',
            name='rounds',
        ),
    ]
