# Generated by Django 5.2.17 on 2026-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, choices=[('a1', 'آواتار 1'), ('a2', 'آواتار 2'), ('a3', 'آواتار 3'), ('a4', 'آواتار 4'), ('a5', 'آواتار 5'), ('a6', 'آواتار 6'), ('a7', 'آواتار 7'), ('a8', 'آواتار 8'), ('a9', 'آواتار 9'), ('a10', 'آواتار 10'), ('a11', 'آواتار 11'), ('a12', 'آواتار 12')], max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='device_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='نام نمایشی'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'زن'), ('M', 'مرد')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_change_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
