# Generated by Django 5.2.17 on 2026-09-22 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_backfill_room_owner'),
        ('users', '0003_block_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('ACCEPTED', 'دوست'), ('DECLINED', 'رد شده')], default='PENDING', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='users_frien_status_48e94b_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_friendship_direction'), models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='no_self_friendship')],
            },
        ),
    ]
