# Generated by Django 5.2.17 on 2026-09-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_played_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
