# Generated by Django 5.2.17 on 2026-09-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, unique=True)),
                ('severity', models.CharField(choices=[('MASK', 'پوشاندن'), ('BLOCK', 'رد کردن پیام')], default='MASK', max_length=5)),
                ('whole_word', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('word',),
            },
        ),
    ]
