# Generated by Django 5.2.17 on 2026-09-22 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'در جریان'), ('ENDED', 'تمام\u200cشده')], default='ACTIVE', max_length=8)),
                ('turn_order', models.JSONField(default=list)),
                ('turn_index', models.PositiveIntegerField(default=0)),
                ('rounds', models.PositiveSmallIntegerField(default=3)),
                ('category', models.CharField(blank=True, choices=[('FRIENDLY', 'دوستانه'), ('FUNNY', 'خنده\u200cدار'), ('DEEP', 'عمیق'), ('BOLD', 'جسورانه')], max_length=10)),
                ('max_intensity', models.PositiveSmallIntegerField(default=2)),
                ('used_prompt_ids', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=32)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='chat.conversation')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRUTH', 'حقیقت'), ('DARE', 'جرئت')], max_length=5)),
                ('text', models.TextField(unique=True)),
                ('category', models.CharField(choices=[('FRIENDLY', 'دوستانه'), ('FUNNY', 'خنده\u200cدار'), ('DEEP', 'عمیق'), ('BOLD', 'جسورانه')], default='FRIENDLY', max_length=10)),
                ('intensity', models.PositiveSmallIntegerField(default=1)),
                ('min_players', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type', 'category', 'intensity', 'is_active'], name='game_prompt_type_15eac7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('CHOOSING', 'در حال انتخاب'), ('ANSWERING', 'در حال پاسخ'), ('REVIEW', 'واکنش دیگران'), ('DONE', 'انجام شد'), ('SKIPPED', 'رد شد')], default='CHOOSING', max_length=10)),
                ('choice', models.CharField(blank=True, choices=[('TRUTH', 'حقیقت'), ('DARE', 'جرئت')], max_length=5)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.prompt')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='game.gamesession')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['conversation', 'status'], name='game_gamese_convers_80dec5_idx'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(fields=('session', 'index'), name='unique_turn_index'),
        ),
    ]
