# Generated by Django 5.2.17 on 2026-09-22 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='deadline_at',
        ),
        migrations.AlterField(
            model_name='turn',
            name='status',
            field=models.CharField(choices=[('CHOOSING', 'در حال انتخاب'), ('ANSWERING', 'در حال پاسخ'), ('CONFIRMING', 'در انتظار تأیید'), ('DONE', 'انجام شد'), ('SKIPPED', 'رد شد')], default='CHOOSING', max_length=10),
        ),
        migrations.CreateModel(
            name='TurnConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='game.turn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('turn', 'user'), name='unique_turn_confirmation')],
            },
        ),
    ]
