# Generated by Django 5.2.17 on 2026-09-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_review_to_confirming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='rounds',
        ),
    ]
