# Generated by Django 5.2.17 on 2026-09-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_backfill_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cleared_before_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
